name: Get Artifact Info
description: >
  Get the information on uploaded artifacts, including download link and size.
author: AHW214
inputs:
  github-token:
    required: true
    description: >
      [String] Token for communicating with the GitHub API.
  debug:
    required: false
    description: >
      [Bool] Whether to log GitHub API calls in the action output.
outputs:
  artifact-info-object:
    description: >
      [JSON] A JSON object with artifact info, in the format
      { [name]: { name: string, size: string, url: string } }.
  artifact-info-array:
    description: >
      [JSON] A JSON array with artifact info, in the format
      [ { name: string, size: string, url: string } ].
runs:
  using: 'node12'
  main: '../dist/action/get-artifact-links/run.js'
